backend:
    name: github
    repo: weston-samuel/yptproject
    branch: master
publish_mode: editorial_workflow
media_folder: "static/images/upload"
public_folder: "/images/uploads"
collections:
    - name: "posts"
      label: "Post"
      folder: "content/posts"
      create: true
      slug: "{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Body", name: "body", widget: "markdown"}
